- name: Download phpMyAdmin
  get_url:
    url: "{{ download_url }}"
    dest: "{{ download_path }}"

- name: Creating a directory for phpmyadmin
  file:
    path: "{{ phpmyadmin_directory }}"
    state: directory
    recurse: yes 

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: "{{ download_path }}/phpMyAdmin-5.1.1-all-languages.tar.gz"
    dest: "{{ phpmyadmin_directory }}"
    remote_src: yes

- name: Copy files 
  copy: 
    src: "{{ phpmyadmin_directory }}/phpMyAdmin-5.1.1-all-languages/"
    dest: "{{ phpmyadmin_directory }}" 
    remote_src: yes 

- name: Creating a configuration file for a virtual domain NGINX
  template: 
    src: phpMyAdmin.conf.j2
    dest: "{{ path_phpMyAdmin_conf }}"
  notify:
    - Restarted NGINX

- name: Setting the owner for the directory
  file:
    path: "{{ phpmyadmin_directory }}"
    state: directory
    recurse: yes 
    owner: www-data
    group: www-data